before_script:
  - pip install docker-auto-labels

stages:
  - lint
  - documentation
  - test
  - build
  - integration
  - release
  - deploy

precommit:
  stage: lint
  image: python:3.11
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    - pip install -q pre-commit
  script:
    - pre-commit run --show-diff-on-failure --color=always --all-files

pytest:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements/prod.txt
  script:
    - python /app/app/tests_pre_start.py
    - pytest --cov=app --cov-report=term-missing app/tests
  after_script:
    - echo "Pytest tests complete"
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  tags:
    - build
    - test

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - apk update && apk add git
  script:
    - docker build -t ${DOCKER_REGISTRY}/trader/tds:${CI_COMMIT_SHORT_SHA} -f backend/backend.dockerfile backend
  only:
    - stag
    - main
  tags:
    - build
    - test
