default_context:
  project_name: 'Mock AI chat'
  project_slug: 'mac'
  domain_main: 'mac.smb-h.com'
  domain_staging: 'stag.mac.smb-h.com'
  docker_swarm_stack_name_main: 'mac-smb-h-com'
  docker_swarm_stack_name_staging: 'stag-mac-smb-h-com'
  secret_key: 'this_is_secret'
  first_superuser: 'admin@mac.smb-h.com'
  first_superuser_password: 'this_is_pass'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mac.smb-h.com", "https://stag.mac.smb-h.com", "https://mac.smb-h.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mac.smb-h.com'
  postgres_password: 'this_is_pass'
  pgadmin_default_user: 'admin@mac.smb-h.com'
  pgadmin_default_user_password: 'this_is_pass'
  traefik_constraint_tag: 'mac.smb-h.com'
  traefik_constraint_tag_staging: 'stag.mac.smb-h.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:this_is_pass'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  _copy_without_render: [backend/app/app/email-templates/**]
  _template: ./
