"""Update Msg table

Revision ID: 2d4a65ba387d
Revises: 4a1ca369783c
Create Date: 2023-11-03 17:16:17.316781

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d4a65ba387d"
down_revision = "4a1ca369783c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "msg",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interaction_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_msg_id"), "msg", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_msg_id"), table_name="msg")
    op.drop_table("msg")
    # ### end Alembic commands ###
