"""Update

Revision ID: 54dca5c1014c
Revises: 5b823f89e100
Create Date: 2023-11-01 12:37:36.257529

"""
# import sqlalchemy as sa

# from alembic import op

# revision identifiers, used by Alembic.
revision = "54dca5c1014c"
down_revision = "5b823f89e100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
