"""Add column MSG and Interactions

Revision ID: 5b823f89e100
Revises: 5f8c77d027d7
Create Date: 2023-11-01 12:27:30.440071

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b823f89e100"
down_revision = "5f8c77d027d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interaction", sa.Column("prompt", sa.String(), nullable=True)
    )
    op.add_column(
        "interaction", sa.Column("model_name", sa.String(), nullable=True)
    )
    op.add_column("interaction", sa.Column("role", sa.String(), nullable=True))
    op.add_column(
        "interaction", sa.Column("created_at", sa.String(), nullable=True)
    )
    op.add_column(
        "interaction", sa.Column("updated_at", sa.String(), nullable=True)
    )
    op.drop_index("ix_interaction_description", table_name="interaction")
    op.drop_index("ix_interaction_title", table_name="interaction")
    op.create_index(
        op.f("ix_interaction_prompt"), "interaction", ["prompt"], unique=False
    )
    op.drop_column("interaction", "title")
    op.drop_column("interaction", "description")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interaction",
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "interaction",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_interaction_prompt"), table_name="interaction")
    op.create_index(
        "ix_interaction_title", "interaction", ["title"], unique=False
    )
    op.create_index(
        "ix_interaction_description",
        "interaction",
        ["description"],
        unique=False,
    )
    op.drop_column("interaction", "updated_at")
    op.drop_column("interaction", "created_at")
    op.drop_column("interaction", "role")
    op.drop_column("interaction", "model_name")
    op.drop_column("interaction", "prompt")
    # ### end Alembic commands ###
