"""Add column last_name to User model

Revision ID: 5f8c77d027d7
Revises: d4867f3a4c0a
Create Date: 2023-11-01 11:20:52.667082

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f8c77d027d7"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_description"),
        "interaction",
        ["description"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_id"), "interaction", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_title"), "interaction", ["title"], unique=False
    )
    op.drop_index("ix_item_description", table_name="item")
    op.drop_index("ix_item_id", table_name="item")
    op.drop_index("ix_item_title", table_name="item")
    op.drop_table("item")
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "item",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "owner_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="item_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="item_pkey"),
    )
    op.create_index("ix_item_title", "item", ["title"], unique=False)
    op.create_index("ix_item_id", "item", ["id"], unique=False)
    op.create_index(
        "ix_item_description", "item", ["description"], unique=False
    )
    op.drop_index(op.f("ix_interaction_title"), table_name="interaction")
    op.drop_index(op.f("ix_interaction_id"), table_name="interaction")
    op.drop_index(op.f("ix_interaction_description"), table_name="interaction")
    op.drop_table("interaction")
    # ### end Alembic commands ###
