"""Update model_name to agent

Revision ID: 993db43f318f
Revises: f266445d8223
Create Date: 2023-11-01 17:48:15.549972

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "993db43f318f"
down_revision = "f266445d8223"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interaction", sa.Column("agent", sa.String(), nullable=True)
    )
    op.drop_column("interaction", "model_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interaction",
        sa.Column(
            "model_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("interaction", "agent")
    # ### end Alembic commands ###
